
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xadd.h"

/*
* The configuration table for devices
*/

XAdd_Config XAdd_ConfigTable[XPAR_XADD_NUM_INSTANCES] =
{
	{
		XPAR_ADD_0_DEVICE_ID,
		XPAR_ADD_0_S_AXI_CONTROL_BASEADDR
	}
};


