
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaddeq.h"

/*
* The configuration table for devices
*/

XAddeq_Config XAddeq_ConfigTable[XPAR_XADDEQ_NUM_INSTANCES] =
{
	{
		XPAR_ADDEQ_0_DEVICE_ID,
		XPAR_ADDEQ_0_S_AXI_CONTROL_BASEADDR
	}
};


