# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/XILINX_BASYS_3/XILINX_BASYS_3.srcs/sources_1/bd/CPU_1/ip/CPU_1_xbar_0/CPU_1_xbar_0.xci
# IP: The module: 'CPU_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/XILINX_BASYS_3/XILINX_BASYS_3.gen/sources_1/bd/CPU_1/ip/CPU_1_xbar_0/CPU_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/GitHub/XILINX_BASYS_3/XILINX_BASYS_3.srcs/sources_1/bd/CPU_1/ip/CPU_1_xbar_0/CPU_1_xbar_0.xci
# IP: The module: 'CPU_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/XILINX_BASYS_3/XILINX_BASYS_3.gen/sources_1/bd/CPU_1/ip/CPU_1_xbar_0/CPU_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
